runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  secure: always
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js
  secure: always
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Access-Control-Allow-Origin: '*'
