runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js
  secure: always

- url: /
  static_files: main.html
  upload: main.html
  secure: always

- url: /.*
  static_files: main.html
  upload: main.html
  secure: always
